# api/config/schema.yaml
# The list of types and properties we want to use
types:
  # Parent class of Person
  Thing:
    properties:
      name: ~
  Person:
    # Enable the generation of the class hierarchy (not enabled by default)
    parent: ~
    properties:
      familyName: ~
      givenName: ~
      additionalName: ~
      address: ~
  PostalAddress:
    properties:
      # Force the type of the addressCountry property to text
      addressCountry: { range: 'Text' }
      addressLocality: ~
      addressRegion: ~
      postOfficeBoxNumber: ~
      postalCode: ~
      streetAddress: ~